import pandas as pd

configfile: "resources/configfile.yaml"
localrules: all, index_reference, generate_complete_report

REFERENCE = config["reference"]
MULTIQC_CONFIG = "multiqc_config.yaml"
KRAKEN_DB = "/PHShome/nm104/db/k2_standard-8"

samples = pd.read_csv( config["samples_file"] )
samples = samples.loc[samples["cell"]!="plate0-D10"]
SAMPLES = samples.set_index( "cell" )[["read1", "read2"]].to_dict( orient="index" )

ORIGINAL_SAMPLES = dict()
for sample, df in samples.groupby( "sample" ):
    ORIGINAL_SAMPLES[sample] = df["cell"].to_list()

rule all:
    input:
        consensus = expand( "results/consensus/{sample}.consensus.fasta", sample=SAMPLES ),
        qc_result = "results/reports/qc_report.html",
        consensus_distances = "results/reports/consensus_distances.csv",
#        assembly = expand( "intermediates/illumina/assembly/{sample}.assembly.fasta", sample=SAMPLES )
        coverages = "results/coverage_subsample.csv",
        #kraken_report = "results/reports/kraken2_reports.csv",
        #bracken_report = "results/reports/bracken2_reports.csv",
        variant_report = "results/variants_subsample.csv"


rule index_reference:
    message: "Indexing {input.reference} for faster access."
    input:
        reference=REFERENCE
    output:
        reference_index=expand(
            REFERENCE + '.{extension}',extension=["bwt", "pac", "ann", "amb", "sa"]
        )
    shell:
        """
        bwa index {input.reference}
        """

include: "rules/reference-assembly.smk"
#include: "rules/denovo.smk"
include: "rules/metagenomic.smk"
include: "rules/subsample_reads.smk"
